from pathlib import Path

import nbformat as nbf


PROJECT_ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK_PATH = PROJECT_ROOT / "notebooks" / "does_algorithm_hide_europe_realdata.ipynb"

FULL_MARKER = "<!-- full-analysis-section -->"


def md(source: str):
    return nbf.v4.new_markdown_cell(source.strip())


def code(source: str):
    return nbf.v4.new_code_cell(source.strip())


def remove_existing_full_section(cells):
    cleaned = []
    skip = False
    for cell in cells:
        if cell.cell_type == "markdown" and FULL_MARKER in cell.source:
            skip = True
            continue
        if skip and cell.cell_type == "markdown" and (
            "Interpretation and Next Steps" in cell.source
            or "## 16. Workplan" in cell.source
            or "## 17. Workplan" in cell.source
        ):
            skip = False
            cleaned.append(cell)
            continue
        if skip:
            continue
        cleaned.append(cell)
    return cleaned


def renumber_sections(cell):
    if cell.cell_type != "markdown":
        return cell
    replacements = {
        "## 15. Interpretation and Next Steps": "## 16. Interpretation and Next Steps",
        "## 16. Workplan": "## 17. Workplan",
        "## 17. Proposal Summary": "## 18. Proposal Summary",
        "## 18. References and Library Ledger": "## 19. References and Library Ledger",
        "## 19. Export Outputs": "## 20. Export Outputs",
    }
    for old, new in replacements.items():
        cell.source = cell.source.replace(old, new)
    return cell


FULL_SECTION_CELLS = [
    md(f"""
{FULL_MARKER}
## 15. Full Analysis Run and Extra Caveat Checks

The proposal run above shows the audit architecture. This section loads the heavier full-analysis outputs generated by `scripts/run_full_cultural_prominence_audit.py`.

The full run uses all M3L-20M interaction rows for data preparation and evaluates recommender models on a larger real-data sample of 5,000 eligible users with an expanded candidate universe. This is still computationally bounded, but it is no longer the small proposal smoke test.

Additional caveats requested for the final project are explicitly tracked:

- **Language differences:** main language labels use Wikidata `original language of film or TV show` (P364); `language of work or name` (P407) is tracked separately where available. This does not claim anything about subtitles, dubbing or platform localization.
- **Production country definition:** country labels use Wikidata `country of origin` (P495), which is not the same as production-company control.
- **American-firm involvement:** production companies use Wikidata `production company` (P272); company/headquarters country is used as a proxy check for US-company involvement in otherwise non-US or European-origin films.

Sources for these metadata definitions are cited in the reference ledger below.
"""),
    code("""
full_run_report = pd.read_csv(OUTPUTS / "12_full_run_report.csv")
full_proxy_risk = pd.read_csv(OUTPUTS / "11_metadata_proxy_risk_table.csv")
full_model_comparison = pd.read_csv(OUTPUTS / "12_full_model_comparison.csv")
full_rerank_tradeoff = pd.read_csv(OUTPUTS / "12_full_rerank_tradeoff.csv")

display(full_run_report)

run_counts = full_run_report.set_index("object")["count"].to_dict()
display(Markdown(
    f"**Full-run interpretation.** The larger audit evaluates {int(run_counts['full analysis users']):,} real users, "
    f"{int(run_counts['candidate items']):,} candidate items, {int(run_counts['sample train rows']):,} train rows and "
    f"{int(run_counts['sample test rows']):,} test rows. The run therefore moves beyond the proposal smoke test while staying feasible on a local machine."
))
"""),
    code("""
from IPython.display import Image

display(full_proxy_risk.round(4))
display(Image(filename=str(OUTPUTS / "11_language_country_company_caveats.png")))

proxy = full_proxy_risk.set_index("check")["share"].to_dict()
display(Markdown(
    f"**Caveat interpretation.** Original-language coverage is {proxy['Has original language']:.1%}, but `language of work/name` coverage is only {proxy['Has language of work/name']:.1%}; "
    f"we should therefore treat P364 as the main language proxy and avoid claims about subtitles or dubbing. "
    f"{proxy['Multiple origin countries']:.1%} of items have multiple origin countries, and {proxy['European origin + US company']:.1%} are European-origin films with US-company involvement. "
    "This directly addresses the production-country caveat."
))
"""),
    code("""
display(full_model_comparison.round(4))

full_dashboard = full_model_comparison.copy()
full_dashboard["Absolute PACPG"] = full_dashboard[["PACPG European", "PACPG Non-English", "PACPG Long-tail"]].abs().sum(axis=1)
best_ndcg = full_dashboard.loc[full_dashboard[f"NDCG@{TOP_K}"].idxmax()]
best_pacpg = full_dashboard.loc[full_dashboard["Absolute PACPG"].idxmin()]
best_coverage = full_dashboard.loc[full_dashboard[f"Coverage@{TOP_K}"].idxmax()]

display(Markdown(
    f"**Model interpretation.** In the full run, **{best_ndcg['Model']}** has the highest NDCG@{TOP_K} ({best_ndcg[f'NDCG@{TOP_K}']:.4f}), "
    f"**{best_coverage['Model']}** has the widest catalogue coverage ({best_coverage[f'Coverage@{TOP_K}']:.1%}), and "
    f"**{best_pacpg['Model']}** has the lowest combined absolute PACPG ({best_pacpg['Absolute PACPG']:.4f}). "
    "This is the main empirical table for the proposal deck."
))
"""),
    code("""
display(full_rerank_tradeoff.round(4))
display(Image(filename=str(OUTPUTS / "14_full_utility_vs_prominence_frontier.png")))

rerank_eval = full_rerank_tradeoff.copy()
rerank_eval["Absolute PACPG"] = rerank_eval[["PACPG European", "PACPG Non-English", "PACPG Long-tail"]].abs().sum(axis=1)
best_rerank_ndcg = rerank_eval.loc[rerank_eval[f"NDCG@{TOP_K}"].idxmax()]
best_rerank_pacpg = rerank_eval.loc[rerank_eval["Absolute PACPG"].idxmin()]

display(Markdown(
    f"**Re-ranking interpretation.** Within the lambda sweep, **{best_rerank_ndcg['Model']}** gives the highest NDCG@{TOP_K} "
    f"({best_rerank_ndcg[f'NDCG@{TOP_K}']:.4f}), while **{best_rerank_pacpg['Model']}** gives the lowest combined absolute PACPG "
    f"({best_rerank_pacpg['Absolute PACPG']:.4f}). We present this as a transparent governance trade-off, not as a hidden correction."
))
"""),
    code("""
display(Image(filename=str(OUTPUTS / "12_full_group_exposure_by_model.png")))
display(Image(filename=str(OUTPUTS / "13_full_accuracy_fairness_summary.png")))

exposure_cols_full = [f"European Exposure@{TOP_K}", f"Non-English Exposure@{TOP_K}", f"Long-tail Exposure@{TOP_K}"]
exposure_ranges = []
for col in exposure_cols_full:
    group = col.replace(f" Exposure@{TOP_K}", "")
    low = full_model_comparison.loc[full_model_comparison[col].idxmin()]
    high = full_model_comparison.loc[full_model_comparison[col].idxmax()]
    exposure_ranges.append(f"{group}: {low['Model']}={low[col]:.1%} to {high['Model']}={high[col]:.1%}")

display(Markdown(
    "**Exposure interpretation.** Full-run discounted exposure ranges by group: "
    + "; ".join(exposure_ranges)
    + ". These are the concrete model-level visibility differences we can discuss in the presentation."
))
"""),
    code("""
import shutil

# Restore full-run outputs as the primary proposal outputs after the lighter notebook cells above.
full_output_map = {
    "12_full_model_comparison.csv": "model_comparison.csv",
    "12_full_group_exposure_by_model.png": "08_group_exposure_by_model.png",
    "13_full_accuracy_fairness_summary.png": "09_accuracy_fairness_summary.png",
    "14_full_utility_vs_prominence_frontier.png": "07_utility_vs_prominence_frontier.png",
}
for src_name, dst_name in full_output_map.items():
    src = OUTPUTS / src_name
    dst = OUTPUTS / dst_name
    if src.exists():
        shutil.copyfile(src, dst)

display(Markdown(
    "**Output handoff.** The primary model-comparison CSV and key deck figures now point to the full-run outputs, so a top-to-bottom notebook run ends in the correct deliverable state."
))
"""),
    code("""
source_citation_ledger = pd.DataFrame([
    {
        "source": "M3L-20M / Binge Watch Zenodo dataset",
        "used_for": "Interactions, multimodal features, dataset statistics",
        "citation": "Spillo et al. (2026), Binge Watch: Reproducible Multimodal Benchmarks for MovieLens-10M and 20M",
        "url": "https://zenodo.org/records/18499145",
    },
    {
        "source": "MovieLens 20M / GroupLens",
        "used_for": "MovieLens titles, genres and IMDb ID bridge",
        "citation": "Harper and Konstan (2015), The MovieLens Datasets",
        "url": "https://files.grouplens.org/datasets/movielens/ml-20m-README.html",
    },
    {
        "source": "Wikidata Data Access",
        "used_for": "SPARQL-based cultural metadata enrichment",
        "citation": "Wikidata contributors, data accessed via Wikidata Query Service",
        "url": "https://www.wikidata.org/wiki/Wikidata:Data_access",
    },
    {
        "source": "Wikidata property P495",
        "used_for": "Country of origin / production-country proxy",
        "citation": "Wikidata property: country of origin (P495)",
        "url": "https://www.wikidata.org/wiki/Property:P495",
    },
    {
        "source": "Wikidata property P364",
        "used_for": "Original language of film or TV show",
        "citation": "Wikidata property: original language of film or TV show (P364)",
        "url": "https://www.wikidata.org/wiki/Property:P364",
    },
    {
        "source": "Wikidata property P407",
        "used_for": "Language of work/name caveat for language differences",
        "citation": "Wikidata property: language of work or name (P407)",
        "url": "https://www.wikidata.org/wiki/Property:P407",
    },
    {
        "source": "Wikidata property P272",
        "used_for": "Production company and US-company involvement caveat",
        "citation": "Wikidata property: production company (P272)",
        "url": "https://www.wikidata.org/wiki/Property:P272",
    },
    {
        "source": "European Audiovisual Observatory: European works in the AVMSD",
        "used_for": "AVMSD context: catalogue share and prominence of European works",
        "citation": "European Audiovisual Observatory, European works in the AVMSD",
        "url": "https://www.obs.coe.int/en/web/observatoire/european-works-in-the-avmsd",
    },
    {
        "source": "European Commission AVMSD page",
        "used_for": "Official EU policy framing for audiovisual media services",
        "citation": "European Commission, Audiovisual Media Services Directive",
        "url": "https://digital-strategy.ec.europa.eu/en/policies/audiovisual-and-media-services",
    },
    {
        "source": "Lesota et al. (2024)",
        "used_for": "Schedl-style dynamic feedback-loop logic for country representation drift",
        "citation": "Lesota, Geiger, Walder, Kowald & Schedl (2024), Oh, Behave! Country Representation Dynamics Created by Feedback Loops in Music Recommender Systems",
        "url": "https://arxiv.org/abs/2408.11565",
    },
    {
        "source": "Mansoury et al. (2020)",
        "used_for": "Feedback-loop and bias-amplification framing for repeated recommendation simulations",
        "citation": "Mansoury, Abdollahpouri, Pechenizkiy, Mobasher & Burke (2020), Feedback Loop and Bias Amplification in Recommender Systems",
        "url": "https://arxiv.org/abs/2007.13019",
    },
    {
        "source": "Steck (2018)",
        "used_for": "Calibration logic behind comparing recommendation distributions with user-profile distributions",
        "citation": "Steck (2018), Calibrated Recommendations, RecSys 2018",
        "url": "https://doi.org/10.1145/3240323.3240372",
    },
    {
        "source": "Markus Schedl profile",
        "used_for": "Outcome framing: recommender systems are established; our project adds an audit layer",
        "citation": "Markus Schedl, research profile and expertise areas",
        "url": "https://www.mschedl.eu/",
    },
    {
        "source": "Schedl et al. (2016)",
        "used_for": "Established recommender-system literature reference",
        "citation": "Schedl, Knees, McFee, Bogdanov & Kaminskas (2016), Music Recommender Systems",
        "url": "https://research.jku.at/en/publications/music-recommender-systems/",
    },
])
source_citation_ledger.to_csv(OUTPUTS / "source_citation_ledger.csv", index=False)
display(source_citation_ledger)
"""),
]


def patch_outputs_manifest(cell):
    if cell.cell_type != "code" or "outputs_manifest = [" not in cell.source:
        return cell
    cell.source = cell.source.replace(
        'outputs_manifest = [\n    "00_research_gap_matrix.png",',
        'outputs_manifest = [\n    "00_research_gap_matrix.png",',
    )
    additions = [
        '    "11_language_country_company_caveats.png",',
        '    "11_metadata_proxy_risk_table.csv",',
        '    "12_full_model_comparison.csv",',
        '    "12_full_rerank_tradeoff.csv",',
        '    "12_full_run_report.csv",',
        '    "12_full_group_exposure_by_model.png",',
        '    "13_full_accuracy_fairness_summary.png",',
        '    "14_full_utility_vs_prominence_frontier.png",',
        '    "source_citation_ledger.csv",',
        '    "does_algorithm_hide_europe_proposal_deck.pptx",',
    ]
    if '"11_language_country_company_caveats.png"' not in cell.source:
        cell.source = cell.source.replace(
            '    "10_workplan_gantt.png",\n',
            '    "10_workplan_gantt.png",\n' + "\n".join(additions) + "\n",
        )
    cell.source = cell.source.replace(
        "These outputs are from a proposal-stage real-data run. No synthetic data was used. Wikidata coverage depends on the local cache and the configured proposal query limit. Do not treat the bounded run as final empirical evidence until the full run is executed.",
        "These outputs use real M3L/MovieLens/Wikidata data only. The notebook includes a proposal smoke test and then restores the larger full-run outputs generated by `scripts/run_full_cultural_prominence_audit.py`. The recommender full run uses 5,000 real users and an expanded candidate universe for local-compute feasibility.",
    )
    return cell


def main():
    nb = nbf.read(NOTEBOOK_PATH, as_version=4)
    cells = remove_existing_full_section(nb.cells)

    new_cells = []
    inserted = False
    for cell in cells:
        cell = renumber_sections(cell)
        cell = patch_outputs_manifest(cell)
        new_cells.append(cell)
        if cell.cell_type == "markdown" and cell.source.lstrip().startswith("## 14. Result Dashboard") and not inserted:
            # Insert after the full result-dashboard block, just before interpretation/next steps.
            pass

    final_cells = []
    for idx, cell in enumerate(new_cells):
        if (
            not inserted
            and cell.cell_type == "markdown"
            and "Interpretation and Next Steps" in cell.source
        ):
            final_cells.extend(FULL_SECTION_CELLS)
            inserted = True
        final_cells.append(cell)

    nb.cells = final_cells
    nbf.write(nb, NOTEBOOK_PATH)
    print(f"Added full-analysis section to {NOTEBOOK_PATH}")
    print(f"Cells: {len(nb.cells)}")


if __name__ == "__main__":
    main()
